### ISSUE TITLE
Blocking a hint

### ISSUE THREAD

**Issue by Heimdallr-1** [klikli-dev/modonomicon#116]
**Describe the bug**
When you hover over the images, the tooltip gets blocked by the picture. Check out the screenshot.

**Screenshots**
![Снимок экрана (9)](https://user-images.githubusercontent.com/41973639/233842050-d2cab52d-03a5-417b-b337-32c7f7057ed5.png)

**System (please complete the following information):**
- Modonomicon Version: 1.30.2
- OS: Windows 22H2 | 19045.2846
- Minecraft Version: 1.19.4
- Modpack Link and Version, or list of mods:

**Chunk+Pregenerator-1.19.4-4.2.3
curios-forge-1.19.4-5.1.5.0
geckolib-forge-1.19.4-4.1.3
Jade-1.19.4-forge-10.0.0
jei-1.19.4-forge-13.1.0.6
modonomicon-1.19.4-1.30.2
occultism-1.19.4-1.74.0
rubidium-0.6.4
rubidium-extra-0.4.18+mc1.19.4-build.84
SmartBrainLib-forge-1.19.4-1.9
starlight-1.1.1+forge.cf5b10b**

**Comment by klikli-dev** [comment]
Thanks for reporting @Heimdallr-1, next release ( https://github.com/klikli-dev/modonomicon/actions/runs/4807246824 ) fixes it
