### ISSUE TITLE
[Suggestion] Port to 1.16.5

### ISSUE THREAD

**Issue by viminio** [klikli-dev/modonomicon#129]
I would like to know if it's possible to port to 1.16.5, if it's too complicated you don't need it, thanks

**Comment by klikli-dev** [comment]
@viminio Currently no backport is planned as on the one hand its a lot of work (huge render differences), and on the other hand 1.16 has not been supported by forge in a long time.
If someone wants to do a port they are welcome to do so and I would also accept the PR to have it in this repo, but I do not have the time to support it myself
