### ISSUE TITLE
Cycle through blocks in tag in pentacle preview and render

### ISSUE THREAD

**Issue by theboo** [klikli-dev/modonomicon#131]
**Is your feature request related to a problem? Please describe.**
people don't realize they can use any candle in the `minecraft:candles` block tag. Same goes for custom pentacles using block tags for certain blocks.

**Describe the solution you'd like**
would be cool if both the in world render and in-book preview cycled through blocks in the tag being used... So for candles they would cycle through every block in `minecraft:candles`

**Additional context**

**Comment by klikli-dev** [comment]
@theboo  I just checked and the tag renderer already does it!
However occultism explicitly sets a display tag in its pentacles, something that was grandfathered in from generating them for patchouli. Will close this here and adjust on occultism!
