### ISSUE TITLE
Book marks and a Favorite page.

### ISSUE THREAD

**Issue by Ciege666** [klikli-dev/modonomicon#142]
**Is your feature request related to a problem? Please describe.**
Surround the Modonomicon with 8 pieces of paper to add 8 book marks to right side of the opened Modonomicon
Shapeless Gold nugget + Modonmicon 'favorite page' allows the player to always open to a specific page when enabled (such as the index)

**Additional context**
The favorite page given by the gold nugget should have a toggle option for the 'pin.'
Favorite page and book marks would be displayed by a gold nugget in a box and book and quill for the favorites.
Shift click the gold nugget to enable and set a golden page. 
Click the gold nugget to toggle favorite page on and off. (brightens the box and nugget when on)

**Comment by klikli-dev** [comment]
More details from https://github.com/klikli-dev/modonomicon/issues/180

> Describe the solution you'd like
The right sidebar of the page is very empty. This could be a great place to store bookmarks to specific entries. Maybe per-category, or just globally

![309483329-df9631c3-61b0-4308-8d43-e01acb8d1ecc](https://github.com/klikli-dev/modonomicon/assets/60774993/78dadf6a-b5d1-4acc-ad34-956f2038b05e)

**Comment by klikli-dev** [comment]
Closing this in favour of #218 which works a bit differently but adds easily accessible bookmarks that are easier to implement
