### ISSUE TITLE
[Fabric] Books are always in the Modonomicon tab, even when custom tab is enabled

### ISSUE THREAD

**Issue by thomasglasser** [klikli-dev/modonomicon#143]
**Describe the bug**
When specifying the "creative_tab" field, the book still stays in the mod tab

**To Reproduce**
1. Specify "creative_tab" field with any vanilla tab
2. Run Fabric
5. See error

**Expected behavior**
The book shows up in the specified tab

**System (please complete the following information):**
- Modonomicon Version: Fabric 1.38.1
- OS: Windows 11
- Minecraft Version: 1.20.1

**Comment by klikli-dev** [comment]
@thomasglasser good find!
I misunderstood / didn't properly think about how the fabric creative mode event works .. so only the modonomicon tab is the only one that was even touched

**Comment by klikli-dev** [comment]
![image](https://github.com/klikli-dev/modonomicon/assets/60774993/4afdd2f7-1c9e-4ad6-a10c-5a6d5dde42e7)
Looks like we got it now
