### ISSUE TITLE
1.20.1 crash on world loading

### ISSUE THREAD

**Issue by hallool** [klikli-dev/modonomicon#145]
**Describe the bug**
crash on world loading

upgrade to 1.38.6

**Expected behavior**
load the world so you can play

**System (please complete the following information):**
- Modonomicon Version: 1.38.6
- OS: [e.g. Windows] win11
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: cant find modlist but they are listed here i hope all   [latest.log](https://github.com/klikli-dev/modonomicon/files/12153116/latest.log)

**Additional context**

The game crashed whilst exception in server tick loop
Error: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract net.minecraft.world.item.ItemStack getRecipeOutput(net.minecraft.world.level.Level, net.minecraft.world.item.crafting.Recipe)' of abstract class com.klikli_dev.modonomicon.book.page.BookRecipePage.

**Comment by klikli-dev** [comment]
@hallool make sure to update occultism and theurgy to their latest versions on 1.20 

This error happens if a mod that uses modonomicon is outdated

**Comment by hallool** [comment]
actually need to upgrade forge im on 47.1.3 bcs many mods are using it like applied energistics2 rf tools/addons

**Comment by klikli-dev** [comment]
I would recommend not to upgrade from 47.1.3, anything above it is pretty broken

**Comment by hallool** [comment]
yeah thats why i didnt but still everything crashes there are 5 mods i can not update no matter what.. this one is is one of them.

**Comment by hallool** [comment]
and occultism and theurgy

**Comment by klikli-dev** [comment]
Modonomicon, Occultism and Theurgy all work on Forge 47.1.3 on their latest version, and in their latest versions should be compatible. Until 1h ago there was a bug where the occultism book did not work, but that did not cause a crash and is fixed now.

Please update all of them to their latest version and try! 
I tried yesterday by adding Theurgy to ATM 9 and it worked

**Comment by klikli-dev** [comment]
@hallool
