### ISSUE TITLE
[1.20.1] Crash on opening Occultism book entry when Theurgy is present

### ISSUE THREAD

**Issue by Gronglegrowth** [klikli-dev/modonomicon#146]
**Describe the bug**
The game appears to crash when attempting to open the entry about demon's dream and divination in the Dictionary of Spirits from occultism, when Theurgy is also present. It produces an error in the book when the game has loaded again.

**To Reproduce**
1. Obtain the Dictionary of Spirits
2. Attempt to open the entry mentioned above
3. Game crashes
4. Reload the game
5. Open book again
6. See the error message instead of the proper entry

**Expected behavior**
The entry should load without issue, and display its contents properly.

**Screenshots**
![Screenshot of the book error](https://github.com/klikli-dev/modonomicon/assets/32804557/dcac5237-5e82-4518-b009-d490d452a0db)

**System (please complete the following information):**
- Modonomicon Version: 1.38.6
- OS: Linux
- Minecraft Version: 1.20.1; forge 47.1.3
- Modpack Link and Version, or list of mods: Occultism 1.81.6; Theurgy 1.4.11; rest of mods can be found in the crashlog below

**Additional context**
[Relevant crashlog](https://github.com/klikli-dev/modonomicon/files/12167473/crash-2023-07-25_22.40.35-client.txt)

**Comment by klikli-dev** [comment]
Thank you for reporting, it was an issue with occultism's book linking to a no longer existing entry in theurgy.

Fixed in https://github.com/klikli-dev/occultism/commit/c332d3a7c7297889873b9961ce14ed1a3c6f20a4

Simply update occultism to use the book again!
