### ISSUE TITLE
[1.20.1] Crash when entering world.

### ISSUE THREAD

**Issue by Gbergz** [klikli-dev/modonomicon#147]
**Describe the bug**
Client crashes when entering  a world.

**To Reproduce**
1. Install mod.
2. Go into a world.
3. Wait.
4. Crash.

**Expected behavior**
No crash when entering world.

**Screenshots**
None.

**System (please complete the following information):**
- Modonomicon Version: 1.39.0
- OS: [e.g. Windows] Windows 11
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: https://gist.githubusercontent.com/Gbergz/f6bd6d843f0952939ba313d4f38041af/raw/03f50b68b65ad7a9a0811efc176d322743a90793/gistfile1.txt

**Additional context**
None.

**Comment by klikli-dev** [comment]
@Gbergz please provide the log file (the one from the time of the crash if there are multiple) and crash report from your minecraft instance /logs and /crashstack folder

**Comment by Gbergz** [comment]
Oh wow, my bad. Forgot the crash report & logs while making this, was really tired at the time.

Here they are,
**Crash-Report**: https://gist.githubusercontent.com/Gbergz/5e7918eaa6ee9ce3b293a3a6d2644802/raw/320efde3dafa0f3a812d848b27b21abae0e26b8f/gistfile1.txt
**Logs:** https://gist.githubusercontent.com/Gbergz/a173ad5ae94e26c3699e451f7b6d5f37/raw/d6f4e84026bb7ae1fdf664670c712005fe2d83df/gistfile1.txt

**Comment by klikli-dev** [comment]
@Gbergz thanks!
This error indicates that you are using a mod that uses modonomicon, but did not account for a recent change in modonomicon.
In the list it shows that you are using an older version of occultism, so that is the likely culprit, if you update it it will be fixed. 

If the error remains then there are other mods using modonomicon that need to be updated

**Comment by Gbergz** [comment]
Seems that was it, CurseForge launcher didn't want to show me new updates for Occultism it seems. Re-downloaded it and now all is fine. Hopefully no more issues rise up. Thanks!

**Comment by klikli-dev** [comment]
Glad to hear that!
