### ISSUE TITLE
NullPointerException when Rendering BookPage in Modonomicon

### ISSUE THREAD

**Issue by windy664** [klikli-dev/modonomicon#148]
### Describe the bug
A crash occurs when rendering a specific page in the Modonomicon. The crash report indicates a `java.lang.NullPointerException` in the `BookPageRenderer.renderTitle` method.

### To Reproduce
Steps to reproduce the behavior are currently unknown. The crash report does not provide explicit steps leading up to the crash.

### Expected behavior
The expected behavior is that the Modonomicon book page renders without any issues or crashes.

### Screenshots
Not available.

### System (please complete the following information):
- **Modonomicon Version:** 1.20.1-forge-1.39.0
- **OS:** Windows 11
- **Minecraft Version:** 1.20.1
- **Modpack Link and Version:** Not provided in the crash report.

### Additional context
The crash seems to be related to a `NullPointerException` when trying to render a title in the Modonomicon book. The underlying cause might
[crash-2023-08-31_11.23.51-client.txt](https://github.com/klikli-dev/modonomicon/files/12481988/crash-2023-08-31_11.23.51-client.txt)
 be a missing or null component.

**Comment by klikli-dev** [comment]
@windy664 thank you for reporting 
Do you happen to know which modonomicon was opened, and which page? 
I can probably fix the error without that info, but I might be able to prevent follow up issues (such as missing titles) if I know where it comes from

**Comment by windy664** [comment]
> @windy664 thank you for reporting Do you happen to know which modonomicon was opened, and which page? I can probably fix the error without that info, but I might be able to prevent follow up issues (such as missing titles) if I know where it comes from

https://github.com/klikli-dev/occultism/issues/970

After my testing, it can be opened during a single-player game, but when I open any pages, it will crash

**Comment by klikli-dev** [comment]
Ah I missed the connected issue, thank you!

**Comment by windy664** [comment]
![R HRF(2XDXBFCWP67P@NR`N](https://github.com/klikli-dev/modonomicon/assets/81475218/bb66d717-bf11-41b5-98f8-8d52b1e901de)
[crash-2023-09-03_15.43.47-client.txt](https://github.com/klikli-dev/modonomicon/files/12505393/crash-2023-09-03_15.43.47-client.txt)

**Comment by klikli-dev** [comment]
I just updated occultism to fix https://github.com/klikli-dev/occultism/issues/970, please let me know if that also fixes this error or not!
