### ISSUE TITLE
1.20.1 exception in server tick loop - Out of memory

### ISSUE THREAD

**Issue by kreezxil** [klikli-dev/modonomicon#152]
**Exception in server tick loop** also says it ran out of memory
[crash-2023-11-01_16.17.41-server.txt](https://github.com/klikli-dev/modonomicon/files/13230102/crash-2023-11-01_16.17.41-server.txt)

**Exception in server tick loop** also says it ran out of memory
[crash-2023-11-01_16.43.04-server.txt](https://github.com/klikli-dev/modonomicon/files/13230103/crash-2023-11-01_16.43.04-server.txt)

Forge 47.2.1
MC 1.20.1

Only 58 mods
[Create_1.20.1-1.0.zip](https://github.com/klikli-dev/modonomicon/files/13230127/Create_1.20.1-1.0.zip)

mod list only: https://paste.centos.org/view/4becde38

**Comment by klikli-dev** [comment]
hmm that is odd. Considering that this happens during class loading, is it possible that it simply is not enough memory?
out of memory can indicate a memory leak but may also just mean that there was not enough memory.
What happens if you give it more mem?

**Comment by kreezxil** [comment]
we gave the server 4 GB. I'll try again later with even more ram. yet, i
don't see why with just 58 mods in the pack that ram should even be an
issue.

**Comment by klikli-dev** [comment]
Closing this as stale, if the issue appears again please ping me to reopen
