### ISSUE TITLE
Another Advancement Condition Tooltip Bug

### ISSUE THREAD

**Issue by Cmdpro** [klikli-dev/modonomicon#153]
If you use an advancement condition on a vanilla minecraft advancement it shows the translation key instead of the advancement name, however i know a solution, first of all in the condition change "advancement" to "advancements" in the advancement condition and second, remove the namespace only if the namespace is "minecraft", minecraft does not include "minecraft" in its advancement translation ids, for example minecraft uses advancements.story.enter_the_end.title instead of advancement.minecraft.story.enter_the_end.title

**Comment by klikli-dev** [comment]
Good find! 

Will fix this soon
