### ISSUE TITLE
Crash when opening Multiblock type page with non-existing multiblock id

### ISSUE THREAD

**Issue by DaFuqs** [klikli-dev/modonomicon#158]
**Describe the bug**
Defining a non-existant multiblock in a multiblock type page will crash the game 

**To Reproduce**
2. Create book page of type multiblock and add a non-existing multiblock name there
3. When ingame, open that book page. => Crash

**Expected behavior**
- The game outputting either an error on launch, if multiblock registration info is available at this time already (similar to the other parsing errors)
- The game not crashing when opening a faulty multiblock type page, but instead rendering nothing, or an error text

**System (please complete the following information):**
- Modonomicon Version: modonomicon-1.20.1-fabric-1.42.0
- OS: Windows
- Minecraft Version: 1.20.1

**Comment by DaFuqs** [comment]
I can attach a crash log when I'm back at my dev env

**Comment by klikli-dev** [comment]
Interestingly that is a divergence between fabric and forge - on forge it already behaves as desired, showing the error when opening the book as all other errors. Will investigate! 

EDIT: oddly enough the crash reproduced once, but now it properly shows the error on open ... 
I made a small change to how book building/preprendering works but not sure if that will fix the issue.

Please ping me here to reopen if it persists in the next version, I currently cannot repro it but as I also failed to repro it more than once before the change it means little
