### ISSUE TITLE
Allow for multiblock predicates to not count towards the multiblock block total

### ISSUE THREAD

**Issue by Cmdpro** [klikli-dev/modonomicon#160]
**Is your feature request related to a problem? Please describe.**
In my mod im using a multiblock (for a boss summon) that needs to have empty space above it, i used to be using spaces however that caused the problem of torches not being able to be placed without messing up boss spawning, so i made a predicate that checks if the block is not solid but that made the bar say a ton of blocks were in the multiblock when it was mostly just detecting for emptiness
 
**Describe the solution you'd like**
I think the best way to solve this would be an optional boolean value in the registerPredicate method that is by default true which determines if the predicate would count towards the total block count of the multiblock

**Comment by klikli-dev** [comment]
![image](https://github.com/klikli-dev/modonomicon/assets/60774993/9a081dfd-9fe3-4171-95b0-a9428c91d29d)

Will add it to the predicate matcher json and add this helper to the multiblock provider to make it more convenient to generate.
This way the predicate can be reused in theory and the matcher json governs the behaviour
