### ISSUE TITLE
Crash when using 1.43.3

### ISSUE THREAD

**Issue by thomasglasser** [klikli-dev/modonomicon#161]
**Describe the bug**
Mod crashes when running fabric on newest version

**To Reproduce**
1. Run fabric with mod

**Expected behavior**
Game runs

Log:
https://paste.ofcode.org/33jTTWHmLxLFk3EKjk8mwfY

**System (please complete the following information):**
- Modonomicon Version: 1.43.3
- OS: Windows
- Minecraft Version: 1.20.4 Fabric
- Modpack Link and Version, or list of mods: In log

**Comment by klikli-dev** [comment]
@thomasglasser thank you for the report!
I just tried to set up a minimal install with just modonomicon + REI in curseforge launcher using fabric 1.20.4 and my game runs normal.

My modlist including dependencies looks like this:
![image](https://github.com/klikli-dev/modonomicon/assets/60774993/399201fd-10aa-46fa-bbc3-3f6202f2c593)


Can you try the same and see if the crash happens there for you too?
If not it is likely some mod interaction, in which case I would need to know which mod combination causes it to recreate it and see if I can fix it on my end, or if the other mod needs to help too

**Comment by thomasglasser** [comment]
It seems to have stopped as of 1.46.0
