### ISSUE TITLE
CJK characters cannot be displayed correctly since 1.50.0

### ISSUE THREAD

**Issue by Nylon256** [klikli-dev/modonomicon#169]
**Describe the bug**
CJK characters cannot be displayed correctly since 1.50.0

**To Reproduce**
1. Use any Modonomicon version after this commit https://github.com/klikli-dev/modonomicon/commit/9495dc989cd47575a8d4f5510d7e5a286b23cbd4
2. Right click any Modonomicon book to open menu.
3. Click any button

**Expected behavior**
CJK characters cannot be displayed correctly

**Screenshots**
![image](https://github.com/klikli-dev/modonomicon/assets/19948087/c3cc1a23-66ae-4693-b515-2e48be5267fc)

**System (please complete the following information):**
- Modonomicon Version: 
- OS: Arch Linux
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
curios-forge-5.5.0+1.20.1.jar  modonomicon-1.20.1-forge-1.55.1.jar  SmartBrainLib-forge-1.20.1-1.13.jar
geckolib-forge-1.20.1-4.4.jar  occultism-1.20.1-1.111.0.jar

**Additional context**
before https://github.com/klikli-dev/modonomicon/commit/9495dc989cd47575a8d4f5510d7e5a286b23cbd4 (1.49.1)
![image](https://github.com/klikli-dev/modonomicon/assets/19948087/6d9303e5-5ecf-40f9-b922-5e87dc8f95f7)

**Comment by klikli-dev** [comment]
Oh that is not good at all.
In that version the font changed and it looks like I need fallbackhandling!

**Comment by klikli-dev** [comment]
![image](https://github.com/klikli-dev/modonomicon/assets/60774993/5e4fd35e-18bf-4f7d-8144-9d7182a2bdec)


There is a new setting in the client config where you can add your locale to use the minecraft default font if the modonomicon default one does not work.

I added japanese, chinese and korean locales as default :)
