### ISSUE TITLE
More recipe types support(like item application recipes in Create)

### ISSUE THREAD

**Issue by openforge233** [klikli-dev/modonomicon#170]
If it's achievable,auto-support(once related mods loaded,Modonomicon gets able to show the related page) is needed.Because I'm using [Lychee mod](https://lycheetweaker.readthedocs.io/) which adds many kinds of recipe types.It's can be painful to support every single mod like this.

**Comment by klikli-dev** [comment]
Can you describe in a bit more detail what you mean?
Do you mean out-of-the box recipe pages for mod recipes like they now exist for vanilla?
Or do you mean automatically showing all recipes of one recipe type in modonomicon, like jei does?

**Comment by openforge233** [comment]
The out-of-the box recipe pages for mod recipes like they now exist for vanilla.
Based on my understanding after reading Lavender's wiki, achieving this might require mod API due to technical reasons. So if the automatically support is impossible,cwould kubejs integration be a viable alternative?
![botania](https://github.com/klikli-dev/modonomicon/assets/101873509/0c40fc01-7c17-48cc-b911-c26429f283be)
![possible_effect](https://github.com/klikli-dev/modonomicon/assets/101873509/ad8db43d-3d3d-4619-a928-cd16cdb7d8ea)

**Comment by klikli-dev** [comment]
Is the latter a screenshot from patchouli, or a mockup showing how such a solution could look?

I ask because providing support for many mods out of the box is not really feasible, as a renderer needs to be defined for each mod - just like in JEI.
If another mod found a way to render via JEI I can look into adapting that for Modonomicon, because to my knowledge that is not possible

**Comment by openforge233** [comment]
A mockup showing made with Photoshop.
Sorry to disturb.

**Comment by klikli-dev** [comment]
No worries - it is a good idea, I just don't think it is possible currently.
If you find any mods doing that please let me know and I will see what I can do

**Comment by klikli-dev** [comment]
I am going to close this for now as it seems not viable to me - if someone finds a reference for "hosting" JEI in other UIs we can reopen
