### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by Noaaan** [klikli-dev/modonomicon#180]
**Describe the solution you'd like**
The right sidebar of the page is very empty. This could be a great place to store bookmarks to specific entries. Maybe per-category, or just globally

**Additional context**
![place to put the bookmarks](https://github.com/klikli-dev/modonomicon/assets/4163353/df9631c3-61b0-4308-8d43-e01acb8d1ecc)

**Comment by klikli-dev** [comment]
I will close this in favor of the older existing issue but copied over the details
