### ISSUE TITLE
Certain offsets between entries draw the connection lines wrongly

### ISSUE THREAD

**Issue by DaFuqs** [klikli-dev/modonomicon#185]
**Describe the bug**
With certain offsets between entries, some parts of the line is drawn at a wrong position.

**To Reproduce**
1. Create entry1 at pos x:0, y:0
2. Create entry2 at pos x:3, y:-1
3. In entry2, set entry1 as parent, including `"line_reversed": true`
4. Join game
5. look at the category with those two entries
6. See error (screenshot below)

**Expected behavior**
Arrow and line being drawn correctly

**Screenshots**
![image](https://github.com/klikli-dev/modonomicon/assets/26429514/caf0dc7c-4059-4a17-877f-d5338f78bd05)

**System (please complete the following information):**
- Modonomicon Version: 1.62.0; Fabric
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: Just Modonomicon & Spectrum

**Comment by klikli-dev** [comment]
ok so fun fact, due to me not having thought about the connection render logic for ages I just asked copilot to compare reversed vs non reversed and fix reversed .. and I think it did fix it.
Please let me know if all connections work for you after that change - in the demo book it looks good

**Comment by DaFuqs** [comment]
Looks perfect now, thx!
