### ISSUE TITLE
Book entries opened via search will not get reopened after closing the book

### ISSUE THREAD

**Issue by DaFuqs** [klikli-dev/modonomicon#196]
**Describe the bug**
When a book entry is opened via search, it will not get automatically displayed when the book is reopened after closing.

**To Reproduce**
1. Open Demo Book
2. Open Formatting Category -> Link Formatting Entry
3. Close the book with ESC
4. Open the book again. "Link Formatting Entry" opens automatically ✅
5. Open Demo Book
6. Open Search
7. Find and open Link Formatting Entry
8. Close the book with ESC
9. Open the book again. The main category view is shown, instead of  "Link Formatting Entry" ⛔

**Expected behavior**
The previous state being restored

**System (please complete the following information):**
- Modonomicon Version: 1.67.0; Fabric
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: Just Modonomicon & Spectrum

**Comment by klikli-dev** [comment]
I am looking into this currently and it actually regressed further, now at step 4 the entry does not reopen automatically. Time to research!
