### ISSUE TITLE
Book crush

### ISSUE THREAD

**Issue by PydingAbsorber** [klikli-dev/modonomicon#198]
Crushes when open anything in your base book and book in occultism.
https://bytebin.lucko.me/bQbFPxlI2L

**Comment by klikli-dev** [comment]
Hmm this is a bug that should be almost impossible to happen, it is missing one of the builtin renderers. 

Can you describe more precisely when it crashes? According to the crash log it's after a click.
I tried it on latest forge and I can open and use the book without issue, including random entries. 
The same applies when using the exact neoforge version you are using.

Can you try to reproduce this in a minimal pack with just occultism + dependencies (+ maybe jei/rei)?
It could be that the interaction with another mod causes it somehow

**Comment by klikli-dev** [comment]
I added a patch that *may* help, this could address one of the potential reasons for the issue although it is quite unlikely. But we can hope ;)
