### ISSUE TITLE
Only register the demo book in dev environments

### ISSUE THREAD

**Issue by DaFuqs** [klikli-dev/modonomicon#207]
**Is your feature request related to a problem? Please describe.**
Having Modonomicon present always registers the demo book. In a finished modpack, the demo book is not needed and clutters recipe viewers, as well as the creative gui (since item groups show up will not show up would there not be any entries in them).
Having a way to disable it would be nice.

**Describe the solution you'd like**
Having an option to register the demo book or not, instead of always registering it.
This could be in form of a config option, load conditions, if it is a dev environment, or something else entirely.

**Comment by klikli-dev** [comment]
That was in fact added in the last update for 1.20.6 so I can backport it :)

**Comment by klikli-dev** [comment]
Done!

**Comment by DaFuqs** [comment]
Awesome, ty!
