### ISSUE TITLE
[Bug-ish] Image pages require 256x256 but only render 200x200

### ISSUE THREAD

**Issue by thomasglasser** [klikli-dev/modonomicon#223]
When we discussed it I was told it was a limitation brought over from Patchouli. It would be nice if this limitation were fixed. Using any size image would be nice, whether it renders at that size or scales it. I've listed it as a bug because I consider rendering only a bit of the image an error.

**Comment by klikli-dev** [comment]
That is a fair point. I'll look into that, maybe with a flag that can be set to restore the old behaviour for those (like me) that have a bunch of patchouli images in their books
