### ISSUE TITLE
[1.21] Latest Mod versioon does not load in Forge

### ISSUE THREAD

**Issue by Periam** [klikli-dev/modonomicon#225]
**Describe the bug**
After installing the mod, without anyother mod in the added, the game does not launch, there is an error related to ResourcePackinfo
The issue is not presented on version modonomicon-1.21-forge-1.83.0, this is the one that I left available.
**To Reproduce**
1.Install the Latest version of the mod modonomicon-1.21-forge-1.90.2
2. Launch the game

**Expected behavior**
that the game launch.

**Screenshots**
![image](https://github.com/klikli-dev/modonomicon/assets/13920185/5cad68a7-7481-4591-9d13-e5752a1cae3e)

**System (please complete the following information):**
- Modonomicon Version: modonomicon-1.21-forge-1.90.2.jar
- OS: [e.g. Windows] Windows 11
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods:  NA

**Additional context**
NA

**Comment by klikli-dev** [comment]
@Periam thanks for reporting, I'll investigate what is going on!
