### ISSUE TITLE
Frequent saving and inconsistent time stop in single player

### ISSUE THREAD

**Issue by DaFuqs** [klikli-dev/modonomicon#226]
**Describe the bug**
When opening an entry, the game tick loop stops (mobs stop movin in the background) and the game saves (can be seen in the log).
That seems a bit excessive.
Interestingly, when looking at a category screen, the game resumes as normal.

**To Reproduce**
1. Open a book in singleplayer.
2. Repeatedly open/close it and switch from categories to entries
3. Observe the mc log

**Expected behavior**
The game either stopping time entirely when opening the book, or never (will probably fix the saving automatically)

**Comment by klikli-dev** [comment]
Hmm interesting. I think GUIs have some overridable function that governs this. I'll experiment!
