### ISSUE TITLE
[1.20.1] Exception in server tick loop

### ISSUE THREAD

**Issue by BazZziliuS** [klikli-dev/modonomicon#232]
**Describe the bug**
The server freezes and crashes

**To Reproduce**
It is not known

**Expected behavior**
The server is not crashing

**System (please complete the following information):**
- Modonomicon Version: 1.73.0
- OS: Linux
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: All information is in the crash log

**Additional context**
[Crash-log](https://paste.fuix.net/15whzTl)

**Comment by klikli-dev** [comment]
@BazZziliuS it does not look like the underlying cause is modonomicon. This is an out of memory error, which means your server does not have enough RAM. It just happens to happen when modonomicon is trying to sync state to clients.

There should be various articles on this and configurations that may help, because often there is enough physical RAM but it is not all assigned to the MC server process.

It is still possible that modonomicon somehow causes it, but considering how long the related code has been unchanged it seems unlikely that no one before had the problem

**Comment by BazZziliuS** [comment]
> @BazZziliuS it does not look like the underlying cause is modonomicon. This is an out of memory error, which means your server does not have enough RAM. It just happens to happen when modonomicon is trying to sync state to clients.
> 
> There should be various articles on this and configurations that may help, because often there is enough physical RAM but it is not all assigned to the MC server process.
> 
> It is still possible that modonomicon somehow causes it, but considering how long the related code has been unchanged it seems unlikely that no one before had the problem

Check this log again https://paste.fuix.net/0kWTZOp
There's a problem with the modonomicon timers

**Comment by klikli-dev** [comment]
@BazZziliuS thanks for pointing that out!

Does this mean this issue occurs regularly for you?
The timer is very basic, so on it's own it should not cause problems. 
If there is an underlying other issue that causes books not to be built, there might be runaway timer situation that uses up resources. That is something I can investigate and guard against, but then it would be good to find out how to cause the situation to address the underlying problem

**Comment by klikli-dev** [comment]
I will push a commit that will close this issue in a minute. Please test if it works with that, and especially if any other issues show up. Feel free to ping me here to reopen the issue if the problem remains, or if a new problem pops up, create a new one. Thank you!

**Comment by BazZziliuS** [comment]
> @BazZziliuS thanks for pointing that out!
> 
> Does this mean this issue occurs regularly for you? The timer is very basic, so on it's own it should not cause problems. If there is an underlying other issue that causes books not to be built, there might be runaway timer situation that uses up resources. That is something I can investigate and guard against, but then it would be good to find out how to cause the situation to address the underlying problem

This problem has been terrorizing me for a month now
![image](https://github.com/klikli-dev/modonomicon/assets/18011884/9c1648ef-e9b8-4d7c-b323-3ee2fd063a22)


I do not know how to cause this situation
I'm using your mod as a library for occultism-1.20.1-1.132.1

**Comment by daniel-eder** [comment]
@BazZziliuS dear gods. can you let me know if the recent update fixes it or not? I switched away from timers to control the threads better

**Comment by klikli-dev** [comment]
@BazZziliuS dear gods. Can you let me know if the recent update fixed it?

**Comment by BazZziliuS** [comment]
> @BazZziliuS dear gods. Can you let me know if the recent update fixed it?

I no longer see crash logs with a modomicon. I think everything is fine

**Comment by klikli-dev** [comment]
Excellent, thank you!
