### ISSUE TITLE
[1.21-115NeoForge]Attempted to load client class at server

### ISSUE THREAD

**Issue by ootwclyhe** [klikli-dev/modonomicon#236]
**Describe the bug**
 - Modonomicon (modonomicon) has failed to load correctly
          java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER

- Modonomicon Version: modonomicon-1.21-neoforge-1.96.0.jar
- OS: Windows10
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: 
[crash-2024-07-23_23.33.09-fml.txt](https://github.com/user-attachments/files/16351193/crash-2024-07-23_23.33.09-fml.txt)

**Comment by ootwclyhe** [comment]
https://github.com/klikli-dev/occultism/issues/1167

**Comment by klikli-dev** [comment]
I am a moron, I added the new code but did not remove the crashing old code ...

**Comment by ootwclyhe** [comment]
You may be a little tired, get a rest.
