### ISSUE TITLE
A subtle mistake

### ISSUE THREAD

**Issue by Karashok-Leo** [klikli-dev/modonomicon#238]
https://github.com/klikli-dev/modonomicon/blob/8541e765d394d94dbff21046947e21c08034edb0/common/src/main/java/com/klikli_dev/modonomicon/api/datagen/CategoryProvider.java#L57
should return this.parent.lang(locale), right?:>

**Comment by klikli-dev** [comment]
You are absolutely right! Will fix ASAP
