### ISSUE TITLE
[Feature Request] A event fired when a book entry is first read

### ISSUE THREAD

**Issue by Karashok-Leo** [klikli-dev/modonomicon#239]
I noticed that there are `EntryClickedEvent` and `commandToRunOnFirstRead`.
It would be even better if there was another event fired when a entry is first read.

**Comment by klikli-dev** [comment]
@Karashok-Leo I will add this presently. Please make sure to read the (brief) documentation on the event regarding providing rewards or doing persistent game logic, as the event is not (fully) guaranteed to run only once per entry.

To summarize, if you use the event for rewards, you should store distributed rewards in a savegame to ensure players cannot "double dip".
