### ISSUE TITLE
[1.21] Modonomicon request a JEI for another MC version

### ISSUE THREAD

**Issue by Periam** [klikli-dev/modonomicon#240]
**Describe the bug**
Installing the mod latest version for 1.21, the mod is requesting to install a JEI version for MC 1.21.1

**To Reproduce**
1. Install Latest mod version
2. Install Latest JEI version
3. Launch MC

**Expected behavior**
That the game launch normally

**Screenshots**
![image](https://github.com/user-attachments/assets/a09b51c2-a136-4864-b431-dec4fd0aec4b)

**System (please complete the following information):**
- Modonomicon Version: modonomicon-1.21.1-neoforge-1.99.1
- OS: Windows 11
- Minecraft Version: 1.21 neoforge 21.0.167
- Modpack Link and Version, or list of mods:
- JEI -1.21-neoforge-19.8.2.99 

**Additional context**

[crash-2024-08-19_17.58.07-fml.txt](https://github.com/user-attachments/files/16665310/crash-2024-08-19_17.58.07-fml.txt)

**Comment by klikli-dev** [comment]
Apologies, fixed in e19e3f197225a9d90ea7a32844c4356dc9b50506

**Comment by Periam** [comment]
Thanks
