### ISSUE TITLE
Crash when starting a new world

### ISSUE THREAD

**Issue by belathus** [klikli-dev/modonomicon#25]
**Describe the bug**
Just updated Occultism, which now requires Modonomicon. Tried creating a new world in single player to test when I got a crash instead.

**To Reproduce**
1. Create new world.
2. Crash.

**Expected behavior**
Not crash.

**Screenshots**

**System (please complete the following information):**
- Modonomicon Version: 1.18.2-1.0.17
- OS: Linux Mint
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: A modpack we're making -- with 168 mods. Do you want the whole list copied here? It is in the crash report.

**Additional context**
Crash Report: https://gist.github.com/belathus/3a1142826ed6c2e0742edecb8c3a03b2

**Comment by klikli-dev** [comment]
@belathus thanks for reporting!
I could not repro it in dev, but I think I found the underlying issue. Please test 1.0.18 once it is available on curseforge (should be in a few minutes hopefully) and ping me here or open a new issue if it was not fixed
