### ISSUE TITLE
[1.21/1.21.1] demo book craftable outside of dev

### ISSUE THREAD

**Issue by Linguardium** [klikli-dev/modonomicon#252]
**Describe the bug**
netherstar and book creates demobook. seems the exclusion is set for `recipes` not `recipe`, might be the underlying issue here
https://github.com/klikli-dev/modonomicon/commit/79d7e224416fc9d6dd23b402d3db908eede29d03

**To Reproduce**
craft book and nether star
Click empty result space

**Expected behavior**
nothing happens

**System (please complete the following information):**
- Modonomicon Version: current as of 9 September 2024

**Additional context**
https://github.com/klikli-dev/modonomicon/blob/version/1.21.1/forge/src/main/resources/data/modonomicon/recipe/crafting/demobook.json
https://github.com/klikli-dev/modonomicon/blob/version/1.21.1/neo/src/main/resources/data/modonomicon/recipe/crafting/demobook.json
https://github.com/klikli-dev/modonomicon/blob/version/1.21.1/fabric/src/main/resources/data/modonomicon/recipe/crafting/demobook.json

https://github.com/klikli-dev/modonomicon/blob/version/1.21/forge/src/main/resources/data/modonomicon/recipe/crafting/demobook.json
https://github.com/klikli-dev/modonomicon/blob/version/1.21/fabric/src/main/resources/data/modonomicon/recipe/crafting/demobook.json
https://github.com/klikli-dev/modonomicon/blob/version/1.21/neo/src/main/resources/data/modonomicon/recipe/crafting/demobook.json

**Comment by klikli-dev** [comment]
Good catch, thank you!
I thought i had removed it entirely, but apparently not

EDIT: Moreover, the exclude path is doubly wrong, the "recipes" that you found, but also the double "modonomicon" which only is needed for modonomicon specific data, not recipes
