### ISSUE TITLE
Creative inventory tab moved to 2nd page with certain other mods installed

### ISSUE THREAD

**Issue by JohnGoten** [klikli-dev/modonomicon#253]
**Describe the bug**
With Modonomicon and Mekanism - possibly other mods affected too, AE2 was not - present, the spawn eggs tab moves to the second page of the creative inventory.

**To Reproduce**
1. Install the latest 1.21.1 NeoForge version 21.1.55, Modonomicon 1.106.0 and Mekanism 10.7.7
2. Create/Enter any world
3. Open up the creative inventory
4. See issue as described

**Expected behavior**
Spawn eggs tab remains in the first page as it would be without Modonomicon installed in e.g. a reasonably sized modpack.

**Screenshots**
![2024-09-18_20 48 41](https://github.com/user-attachments/assets/feeb0fb5-02e1-49ef-82c3-b8c54ea69777)
![2024-09-18_20 48 54](https://github.com/user-attachments/assets/6c67bacd-2436-40fd-9645-3a9b677f0f6f)

**System (please complete the following information):**
- Modonomicon Version: 1.106.0
- OS: Windows 11
- Minecraft Version: NeoForge 1.21.1 21.1.55
- Modpack Link and Version, or list of mods: here's my latest log instead > https://mclo.gs/vjZbwXb

**Additional context**
-

**Comment by klikli-dev** [comment]
Hmm I think this is just due to the registration order instructions that neoforge takes for creative tabs. I will check if there is a way to just have the modonomicon tab at the end. Thanks for reporting!

**Comment by klikli-dev** [comment]
It does not reproduce for me, but I removed the creative tab ordering instructions which might help with that.
If it remains it probably needs to be raised with neoforge to see if there is a way to consistently order creative tabs.
