### ISSUE TITLE
Another subtle mistake

### ISSUE THREAD

**Issue by Karashok-Leo** [klikli-dev/modonomicon#255]
https://github.com/klikli-dev/modonomicon/blob/5aeab459b798d01c93a9fd694ac5f0fa78ae0982/common/src/main/java/com/klikli_dev/modonomicon/api/datagen/EntryProvider.java#L36

Same issue as https://github.com/klikli-dev/modonomicon/issues/238

**Comment by klikli-dev** [comment]
I could have sworn I fixed that when I checked #238. 
I need to sleep more! Thanks!
