### ISSUE TITLE
Recipe pages not rendering page text with 2 recipes set

### ISSUE THREAD

**Issue by DaFuqs** [klikli-dev/modonomicon#257]
**Describe the bug**
When using the blasting recipe page like this:
```json
{
  "type": "modonomicon:blasting_recipe",
  "title1": "book.spectrum.guidebook.pure_resources.page1.title",
  "recipe_id_1": "spectrum:blasting/pure_resources/iron",
  "recipe_id_2": "spectrum:blasting/pure_resources/gold",
  "text": "book.spectrum.guidebook.pure_resources.page1.text"
}
```
The recipes and title render, but not the page text.

This is because BookRecipePageRenderer only renders the text when there is no second recipe
https://github.com/klikli-dev/modonomicon/blob/f2b8a0fd71fc55eb30dde78ade7ff3d0f5600ee9/common/src/main/java/com/klikli_dev/modonomicon/client/render/page/BookRecipePageRenderer.java#L52
but that is not reflected [on the wiki](https://klikli-dev.github.io/modonomicon/docs/basics/page-types/recipe-pages).

Looking at a Blasting Recipe page with 2 recipes there is quite some more room which could fit some text. So maybe still rendering the text on the leftover space would be feasible.
![image](https://github.com/user-attachments/assets/d2d32d50-e3bc-4b16-a831-99f19c0c22c5)

**Expected behavior**
1. the wiki being updated

OR

2. the text rendering

**Comment by klikli-dev** [comment]
It is intended behaviour, but not apparently documented currently. 

However, I designed this when doing the normal crafting page, which does not leave as much space. So I think it would be good to add text rendering, I just need to check if that can be done backwards compatible with addon pages (I believe the text offsets on recipe pages need an override in child classes)
