### ISSUE TITLE
Omnibus: Recent Changes

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/modonomicon#261]
- [ ] Fix remaining language adjustments from MuteTiefling's review in #1237
- [ ] Fix https://github.com/klikli-dev/modonomicon/issues/260 and/or choose better blocks for the pentacle using those blocks
- [ ] divination rod config page review: https://github.com/klikli-dev/occultism/pull/1237#issuecomment-2449446307

**Comment by Eqis-Edu** [comment]
> Fix remaining language adjustments from MuteTiefling's review in 1237

About the ritual dummies capitalization I commit now. Check [#1261](https://github.com/klikli-dev/occultism/pull/1246)
About ritual messages ALL (conditions, started, completed and stopped) are in lowercase letters, in ENUSProvider from line 682 to 1097, I don't think it's necessary to change this now.

> Fix 260 and/or choose better blocks for the pentacle using those blocks

Solved the render in 1.108.2. 
Regarding changing blocks, I don't see any problems as long as there are reasons for choosing them. They may seem random and without much sense, but I thought about the motivation for each block when making the choices.

> divination rod config page review: 1237

I think the quote in the comment is wrong, it seems to be talking about the point above
