### ISSUE TITLE
Open to lan issue when genetics resequenced is in a pack

### ISSUE THREAD

**Issue by Gaz492** [klikli-dev/modonomicon#263]
**Describe the bug**
When genetics resequenced is present open to lan no longer works can causes a connection lost message with an encoding error
Debug log: https://pste.me/@s5zYqMTR0_I

**To Reproduce**
1. Create a test modpack with modonomicon and genetics resequenced
2. Go to singleplayer and open to lan
3. With another client try connecting to the lan server

**Expected behavior**
Able to join the lan server without issues.

**Screenshots**
![javaw_2024-11-02_22-33-20](https://github.com/user-attachments/assets/6eae849e-2f3b-4678-b7ac-8194cf645379)

**System (please complete the following information):**
- Modonomicon Version: 1.21.1-neoforge-1.5.0
- OS: Windows
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: genetics resequenced, modonomicon, jei, kotlin for forge

[](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6061)

**Comment by klikli-dev** [comment]
@Gaz492 thanks for reporting!
The author of genetics resequenced and I are currently looking into what I believe to be the underlying issue, namely how to reference the content of datapack registries (the genes) in item stacks (the spotlight page that causes the crash)

**Comment by Saereth** [comment]
Any word on this by chance? @klikli-dev

**Comment by klikli-dev** [comment]
@Saereth Sadly not yet, as I haven't been able to find the required info. I assume some smart people around neoforge know, but I have not found the right person to bug about it. 

Just to confirm, does it happen to you on latest modonomicon + latest genetics?

**Comment by Saereth** [comment]
it does yeah, people were submitting new issues on our tracker about it as recently as yesterday

**Comment by klikli-dev** [comment]
Looking at latest genetics and modonomicon, I think I know how to fix this. Will require an update of genetics, and probably also modonomicon, so it may take a few days to be available

**Comment by Saereth** [comment]
awesome, ty for looking into this!
