### ISSUE TITLE
Entry descriptions do not show in index mode.

### ISSUE THREAD

**Issue by thomasglasser** [klikli-dev/modonomicon#268]
**Describe the bug**
The entry description is never seen in index mode.

**To Reproduce**
1. Make an index mode entry with a description
2. Open entry

**Expected behavior**
The entry description would either be unsupported (as it's currently required) or shown on the first page similar to the category description.

**System (please complete the following information):**
- Modonomicon Version: 1.109.1
- OS: Windows
- Minecraft Version: 1.21.3

**Comment by klikli-dev** [comment]
I think I have to think about that on both fronts.
The descriptions should show on hover (apparently I forgot to set that up), and I *think* they should not be mandatory.
