### ISSUE TITLE
[1.19.2] All toasts are broken

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [klikli-dev/modonomicon#27]
**Describe the bug**
Well, I think it's not a feature and I don't know is this intended or not, but every time I open Image Entry (or any other entry) I see that Image Switcher is moved to the left and go outside of shadow box.
Also all toasts are broken and without text if opening any entry.

**To Reproduce**
1. Get a `test` or `Demo Book` from JEI or whatever example book you have. You can also use an already prepared book with categories and entries.
2. Open it and click on any Image Entry to see Image Switcher shift and/or any other entry with toast in the corner to get broken UI or toast. (a bit of untested, in my test pack text dissapears, in my pack with more 170+ mods with Rubidium and Oculus it happens that random stuff can appear such of random visual artifacts with items/multiblocks and it's hard to get a picture of it, let me know if you need more stuff about this or modlist, but second screenshot is about this)
3. See the bug.

**Expected behavior**
Image Switcher is in the box, Toasts are shown properly and no visual glitches comes

**Screenshots**
![image](https://user-images.githubusercontent.com/27882185/191771212-6f735c02-9d58-4309-9c85-9316b0ac637e.png)
![image](https://user-images.githubusercontent.com/27882185/191775221-d86ca874-a338-4305-9ee7-8ee7bc4e3a2a.png)

**System (please complete the following information):**
- Modonomicon Version: 1.19.2-1.0.18
- OS: Windows 10
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: Just Modonomicon and JEI (confirmed to work with only Modonomicon)
- Screen Resolution: 1920x1080, 2560x1440 (tested both)

**Additional context**
If you need logs or anything, feel free to ping me in the issue.

**Comment by klikli-dev** [comment]
Good finds!
There seems to be a bit of a pattern with some things being shifted to the left (it also affects the "catalyst" in crafting recipes, such as the spirit fire in occultism). 

Weird about the toasts .. I'll have to do some research there I am not sure why they are affected, I fear I am not properly cleaning up after rendering content

**Comment by klikli-dev** [comment]
Note: caused by renderBackground in BookContentScreen

**Comment by klikli-dev** [comment]
@DenisMasterHerobrine it seems this is actually some weird issue with Vanilla/Forge GUI rendering - the vanilla background rendering if used unmodified breaks the toasts. 
I added a fix, but I am not sure if it covers all cases. This issue will be closed, but if possible please test in 1.0.20 if you still have glitches and open a new issue if that is the case - thanks!
