### ISSUE TITLE
Entries broken because of unloaded Advancements

### ISSUE THREAD

**Issue by dphaldes** [klikli-dev/modonomicon#271]
**Describe the bug**
Some entries are locked behind advancements but aren't displayed to the user. The text says "Loading" even in Single-player.
![image](https://github.com/user-attachments/assets/187c7957-c147-46d4-b910-f85ff687fc1e)

**To Reproduce**
Can be seen in Occultism Dictionary of Spirits under pentacles and rituals.

**System (please complete the following information):**
- Modonomicon Version:  1.108.4 
- Occultism: 1.168.0
- OS: [e.g. Windows] : Linux
- Minecraft Version: 1.21.1

**Comment by klikli-dev** [comment]
Thanks! That is concerning
