### ISSUE TITLE
Dynamic Text Placeholders

### ISSUE THREAD

**Issue by DaFuqs** [klikli-dev/modonomicon#274]
**Is your feature request related to a problem? Please describe.**
I have a mod where you can configure the max level of an enchantment in the mods config file.
Reflecting that max level in the guidebook is a bit tricky however.
Currently the max level is baked into that guidebook entry's lang string aka `it has a max level of II`.
When a pack maker updates the config they often forget about updating that lang string, however, making the guidebook and the actual value inconsistent.

**Describe the solution you'd like**
A way to register text content replacement that get inserted when baking the book.
E.g. having a lang text like `it has a max level of {mymod.myenchantment.level}` get's baked into `it has a max level of X` , depending on the value of the config.

Have not thought about the impl yet, mostly just throwing it out there.

**Comment by klikli-dev** [comment]
@DaFuqs definitely a needed feature! 
Can we brainstorm a bit on this?

By and large the replacements would be pretty trivial - basically just a dynamic version of the already existing macro system during datagen (plus maybe some trickery when preparing the markdown rendering)

But how should the values be supplied? Something like a registry where you can register a lambda/callback method that gives you the macro key and you return the replacement text?

**Comment by DaFuqs** [comment]
Some thoughts:
- Since some replacements may be based on dynamic registries - since lots of stuff in 1.21.x has been moved to that - it would be best to do the replacement during the baking of the book after joining a world after those have been registered
- Some values may be based on settings on the server side (enchantent levels, ...), while some may be based on client data (rendering details, ...), so some values might need to be sent from server->client, while others directly grabbed from the client side. Since registries have to be identical between server and client, a synced registry may not be the best option (though the `synced registry` flag would make syncing very easy!)
- I feel like the best bet would be a lookup map that gets queried when baking the book, with the s->c book sync supplying the server values and the client adding their values directly
- Lookup Map vs. Callback: A callback would definitely be even more dynamic than allowing just simple string replacements! Not sure how to supply data from the server side, though. Maybe you have an idea?

**Comment by klikli-dev** [comment]
Currently the baking happens both on client (for displaying) and server (for verification). The baking happens after other data is synced. 

A lookup map could be synced alongside the book data, but would require static known values at baking time.
A callback system could query the value at render time, but with the caveat that the modder would have to take care of data sync. That is not necessarily hard (could be as simple as one packet + some singleton storage), but maybe more work than necessary for most use cases.

**Comment by DaFuqs** [comment]
Yeah, the lower the bar the higher the chance the mechanism is getting used.

As long as the values are pulled from registries (or something else that is synced either way), there is no need for a custom packet. That may catch the most use cases, already?

**Comment by klikli-dev** [comment]
Now I just need to figure out how to splice into the translation system to replace text - or otherwise how to make the markdown parser play things cool

**Comment by klikli-dev** [comment]
![image](https://github.com/user-attachments/assets/98f20173-713b-4cec-a6a9-2d32961eab3e)

**Comment by DaFuqs** [comment]
Whoa, that was quick! Thank you lots!
