### ISSUE TITLE
[1.19.2] Opening a test entry with broken JSON hangs the world and crashes the game

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [klikli-dev/modonomicon#28]
**Describe the bug**
Well, I think that it's JSON issue and/or something have been done wonky when parsing, but when I was learning and playing around Modonomicon, I got several crashes when looking into example entries.

**To Reproduce**
1. Get `test` book and find conditional test entry (with emerald icon). Also you can just simply create an conditional entry without any text.
2. Click on it.
3. Get a frozen MC instance or a crash with a log.
4. See error.

**Expected behavior**
To not crash or handle the NPE and throw an error into both logs and chat to know that the issue is on broken JSON.

**Screenshots**
Not applicable.

**System (please complete the following information):**
- Modonomicon Version: 1.19.2-1.0.18
- OS: Windows 10
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: Modonomicon and JEI (confirmed to work with just Modonomicon)

**Additional context**
If you need logs or anything, feel free to ping me in the issue.
[Crash Report](https://gist.github.com/DenisMasterHerobrine/bdcdcbf2e65cc1451917edafd30bc0e2)

**Comment by klikli-dev** [comment]
Looks to be related to title or body text handling .. probably does not create a default value properly - will look into it, thanks!
