### ISSUE TITLE
Crash: NoClassDefFoundError 1.18.2

### ISSUE THREAD

**Issue by Littlekat4** [klikli-dev/modonomicon#44]
[crash-2022-10-02_22.34.57-fml.txt](https://github.com/klikli-dev/modonomicon/files/9694910/crash-2022-10-02_22.34.57-fml.txt)
Hello This was happening I was hoping you could help thank you :)

**Comment by klikli-dev** [comment]
Hi @Littlekat4, please try updating to latest forge, this is due to a breaking change in forge, mods that use this event and target the newer version like modonomicon do not work with the older
