### ISSUE TITLE
Modonomicon (modonomicon) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by J3zt** [klikli-dev/modonomicon#46]
**Describe the bug**
Loading the mod failed for unknown reasons. Crash report file attatched.

**System:**
- Modonomicon Version: 1.4.1
- OS: Windows
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: 
Occultism: https://www.curseforge.com/minecraft/mc-mods/occultism

[crash-2022-10-03_20.31.10-fml.txt](https://github.com/klikli-dev/modonomicon/files/9700159/crash-2022-10-03_20.31.10-fml.txt)

**Comment by klikli-dev** [comment]
Please try running with latest forge for 1.18.2 (i think 40.1.80), forge had a breaking change when they moved/renamed various events.
Mods that use these events - such as modonomicon - only work with versions after the breaking change.

**Comment by Littlekat4** [comment]
THANK YOU!
